version: '3.7'

services:
  fc_mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fc_video
    ports:
      - "3306:3306"
    networks:
      - fc_network
      
  fc_app:
    build: .
    depends_on:
      - fc_mysql
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    working_dir: /app
    command: ./gradlew bootRun
    networks:
      - fc_network

networks:
  fc_network: